name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"

  ifs-multistring:
    runs-on: ubuntu-latest
    steps:
      - name: read multiline envvar
        env:
          values: |
            abc,
            def xyz
        run: |
          values_single_line=$(echo "$values" | tr '\n' ',')
          echo "single line: $values_single_line"
          IFS=$', ' read -r -a values_array <<< "$values_single_line"
          echo "${values_array[@]}"
          for val in "${values_array[@]}"; do
              value_pretty=$(echo "$val" | tr -d "[:space:]")
              echo "|$val| - |$value_pretty|"
              if [[ -n $val ]]; then
                echo "!! |$val|"
              fi
          done
